apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins-sfs
  namespace: devops-tools
spec:
  serviceName: "jenkins-headless"
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      serviceAccountName: jenkins-admin
      securityContext:
        fsGroup: 1000 
        runAsUser: 1000
      containers:
        - name: jenkins
#          image: jenkins/jenkins:lts
          image: jenkins/jenkins:2.440.1-lts-jdk17
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "1"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          env:
            - name: JAVA_OPTS
              value: >
                -Xms512m
                -Xmx2g
                -XX:+UseG1GC
                -XX:MaxMetaspaceSize=512m
                -XX:+UseAdaptiveSizePolicy
                -XX:MaxHeapFreeRatio=60
                -XX:MinHeapFreeRatio=30
                -XX:+HeapDumpOnOutOfMemoryError
                -XX:HeapDumpPath=/var/jenkins_home
                -XX:+UnlockDiagnosticVMOptions
                -XX:NativeMemoryTracking=summary
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home
  volumeClaimTemplates:
    - metadata:
        name: jenkins-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "local-storage"
        resources:
          requests:
            storage: 10Gi