apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app1
  namespace: ingress-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app1
  template:
    metadata:
      labels:
        app: web-app1
    spec:
      containers:
      - name: web-app1
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app1-service
  namespace: ingress-nginx
spec:
  selector:
    app: web-app1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app2
  namespace: ingress-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-app2
  template:
    metadata:
      labels:
        app: web-app2
    spec:
      containers:
      - name: web-app2
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-app2-service
  namespace: ingress-nginx
spec:
  selector:
    app: web-app2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
