network:
  ethernets:
    eth0:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.40.46/24]
      nameservers:
        addresses:
        -  192.168.40.48
        search: [vsphere.local]
      routes:
        - to: 0.0.0.0/0
          via: 192.168.40.254
  version: 2